"use client";

import React, { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, Download, RefreshCw, ShieldCheck } from "lucide-react";
import { toJalaliDate } from "@/lib/dateUtils";

type Backup = { id: string; filename: string; status: string; checksum: string; sizeBytesBigint?: number | null; sizeBytes: number; schemaVersion?: string | null; gitSha?: string | null; createdAt: string; verifiedAt?: string | null };
type Validation = { backupValid: boolean; checksumValid: boolean; readable: boolean; metadataValid: boolean; backupSchemaVersion: string; currentSupportedSchemaVersion: string; restoreRisk: string; warnings: string[] };

export const BackupView: React.FC = () => {
  const [items, setItems] = useState<Backup[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [selected, setSelected] = useState<Backup | null>(null); const [validation, setValidation] = useState<Validation | null>(null); const [confirmation, setConfirmation] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/backups", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "خطا در دریافت نسخه‌ها"); setItems(body.backups || []); }, []);
  useEffect(() => { load().catch((reason) => setError(reason.message)); }, [load]);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "عملیات ناموفق بود"); } finally { setBusy(false); } };
  const request = async (url: string, body?: unknown) => { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "عملیات ناموفق بود"); return data; };

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-xl font-bold text-white"><Database className="h-6 w-6 text-blue-400" />پشتیبان‌گیری و بازیابی PostgreSQL</h2><button disabled={busy} onClick={() => run(async () => { await request("/api/backups", {}); })} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">ایجاد نسخه پشتیبان</button></div>
    <div className="rounded-2xl border border-blue-500/30 bg-blue-950/20 p-4 text-sm leading-6 text-slate-300"><ShieldCheck className="ml-2 inline h-5 w-5 text-blue-400" />نسخه‌ها با فرمت native PostgreSQL، checksum از نوع SHA-256 و فایل‌های خارج از public ایجاد می‌شوند.</div>
    {error && <div className="rounded-xl border border-red-500/30 bg-red-950/30 p-3 text-sm text-red-200">{error}</div>}
    <div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-white/5 text-slate-300"><tr><th className="p-3">زمان</th><th className="p-3">وضعیت</th><th className="p-3">حجم</th><th className="p-3">Schema</th><th className="p-3">Checksum</th><th className="p-3">عملیات</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-white/10 text-slate-200"><td className="p-3">{toJalaliDate(item.createdAt, { showTime: true })}</td><td className="p-3">{item.status === "verified" ? <span className="text-emerald-400"><CheckCircle2 className="ml-1 inline h-4 w-4" />تأییدشده</span> : item.status}</td><td className="p-3">{Math.ceil(Number(item.sizeBytesBigint || item.sizeBytes) / 1024).toLocaleString("fa-IR")} KB</td><td className="p-3">{item.schemaVersion || "—"}</td><td className="p-3 font-mono text-xs">{item.checksum.slice(0, 12)}…</td><td className="flex gap-2 p-3"><button disabled={busy} title="بررسی checksum" onClick={() => run(async () => { await request(`/api/backups/${item.id}/verify`); })}><RefreshCw className="h-4 w-4" /></button><a title="دانلود" href={`/api/backups/${item.id}/download`}><Download className="h-4 w-4" /></a><button disabled={busy || item.status !== "verified"} className="text-amber-400" onClick={() => { setSelected(item); setValidation(null); setConfirmation(""); }}>اعتبارسنجی Restore</button></td></tr>)}</tbody></table>{!items.length && <p className="p-6 text-center text-sm text-slate-400">نسخه پشتیبانی ثبت نشده است.</p>}</div>
    {selected && <div className="space-y-4 rounded-2xl border border-amber-500/40 bg-amber-950/20 p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-1 h-5 w-5 shrink-0 text-amber-400" /><div><p className="font-bold text-amber-200">Restore یک عملیات عادی نیست</p><p className="text-sm leading-6 text-slate-300">ابتدا checksum، catalog و schema بررسی می‌شود. Restore فقط به دیتابیس مقصد خالی و مجزا انجام می‌شود و دیتابیس جاری هرگز پاک نمی‌شود.</p></div></div><dl className="grid gap-2 text-sm text-slate-300 md:grid-cols-2"><div>Backup: {toJalaliDate(selected.createdAt, { showTime: true })}</div><div>Size: {selected.sizeBytesBigint || selected.sizeBytes} bytes</div><div>Schema: {selected.schemaVersion}</div><div>Git SHA: {selected.gitSha || "unknown"}</div><div className="break-all md:col-span-2">SHA-256: {selected.checksum}</div></dl><button disabled={busy} onClick={() => run(async () => { const data = await request(`/api/backups/${selected.id}/restore/validate`); setValidation(data.validation); })} className="rounded-xl border border-amber-400 px-4 py-2 text-sm text-amber-200">اجرای Dry-run validation</button>{validation && <div className="rounded-xl bg-black/20 p-4 text-sm text-slate-300"><p>Backup valid: {validation.backupValid ? "بله" : "خیر"}</p><p>Checksum: {validation.checksumValid ? "معتبر" : "نامعتبر"}</p><p>Archive readable: {validation.readable ? "بله" : "خیر"}</p><p>Risk: {validation.restoreRisk}</p>{validation.warnings.map((warning) => <p key={warning} className="text-amber-300">{warning}</p>)}</div>}{validation?.backupValid && <div className="space-y-2"><label className="block text-sm text-slate-300">برای بازیابی آزمایشی روی دیتابیس مقصد مجزا، عبارت <b>RESTORE</b> را وارد کنید.</label><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white" /><button disabled={busy || confirmation !== "RESTORE"} onClick={() => run(async () => { await request(`/api/backups/${selected.id}/restore`, { confirmation }); setSelected(null); })} className="rounded-xl bg-red-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Restore به دیتابیس مجزای تنظیم‌شده</button></div>}</div>}
  </div>;
};
