"use client";
import { useCallback,useEffect,useMemo,useState } from "react";import { AlertOctagon,CheckCircle2,Clock3,Plus } from "lucide-react";
import { JalaliDatePicker } from "@/components/ui/JalaliDatePicker";import { AtelierModal,Field,fieldClass } from "@/components/studio/shared/AtelierModal";import { toJalaliDate } from "@/lib/dateUtils";
type Task={id:string;studioProjectId:string;projectTitle:string;projectNumber:string;title:string;stage:string;priority:string;status:string;dueDate?:string;assigneeName?:string;assignedPersonnelId?:string;blocker?:string;dependencyId?:string};
async function request(url:string,init?:RequestInit){const r=await fetch(url,init),d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'عملیات ناموفق بود.');return d}
export function StudioWorkboard(){const[tasks,setTasks]=useState<Task[]>([]),[projects,setProjects]=useState<any[]>([]),[personnel,setPersonnel]=useState<any[]>([]),[view,setView]=useState('all'),[edit,setEdit]=useState<any>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const q=view==='all'?'':`?view=${view}`;const[a,b,c]=await Promise.all([request('/api/studio/tasks'+q),request('/api/studio/projects?pageSize=100'),request('/api/studio/personnel?pageSize=100')]);setTasks(a.tasks);setProjects(b.projects);setPersonnel(c.personnel)}catch(e:any){setError(e.message)}},[view]);useEffect(()=>{load()},[load]);
 const columns=[['open','باز'],['in_progress','در حال انجام'],['done','تکمیل‌شده']] as const;const overdue=(t:Task)=>t.dueDate&&new Date(t.dueDate)<new Date()&&!['done','cancelled'].includes(t.status);
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{await request(`/api/studio/projects/${edit.studioProjectId}/tasks`,{method:edit.id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(edit)});setEdit(null);load()}catch(e:any){setError(e.message)}};
 const complete=async(t:Task)=>{try{await request(`/api/studio/projects/${t.studioProjectId}/tasks`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...t,status:'done'})});load()}catch(e:any){setError(e.message)}};
 return <div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-black text-white">کارها و گردش‌کار</h1><p className="text-sm text-slate-400">صف کارهای تیم، مهلت‌ها، وابستگی‌ها و موانع</p></div><button onClick={()=>setEdit({studioProjectId:projects[0]?.id||'',title:'',stage:'pre_production',priority:'medium',status:'open',dueDate:'',assignedPersonnelId:'',blocker:'',description:''})} className="flex items-center gap-2 rounded-xl bg-cyan-600 px-4 py-2.5 text-sm font-bold"><Plus className="h-4 w-4"/>کار جدید</button></header>{error&&<p className="rounded-xl bg-rose-950/30 p-3 text-rose-200">{error}</p>}
 <div className="flex gap-2 overflow-x-auto">{[['all','همه'],['today','امروز'],['urgent','فوری'],['overdue','عقب‌افتاده']].map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`rounded-xl px-4 py-2 text-xs font-bold ${view===id?'bg-cyan-600 text-white':'border border-slate-700 text-slate-300'}`}>{label}</button>)}</div>
 <div className="grid gap-4 lg:grid-cols-3">{columns.map(([status,label])=><section key={status} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-3"><h2 className="mb-3 flex justify-between font-bold text-white"><span>{label}</span><span>{tasks.filter(t=>t.status===status).length.toLocaleString('fa-IR')}</span></h2><div className="space-y-2">{tasks.filter(t=>t.status===status).map(t=><article key={t.id} className={`rounded-xl border p-3 ${t.priority==='urgent'?'border-rose-500/50 bg-rose-950/20':overdue(t)?'border-amber-500/40 bg-amber-950/10':'border-slate-800 bg-slate-950'}`}><button onClick={()=>setEdit({...t,dueDate:t.dueDate||''})} className="w-full text-right"><div className="flex items-start justify-between gap-2"><b className="text-sm text-white">{t.title}</b>{t.priority==='urgent'&&<AlertOctagon className="h-4 w-4 shrink-0 text-rose-400"/>}</div><p className="mt-1 text-xs text-cyan-300">{t.projectNumber} · {t.projectTitle}</p>{t.assigneeName&&<p className="mt-2 text-xs text-slate-400">مسئول: {t.assigneeName}</p>}{t.dueDate&&<p className={`mt-2 flex items-center gap-1 text-xs ${overdue(t)?'text-amber-300':'text-slate-400'}`}><Clock3 className="h-3.5 w-3.5"/>{toJalaliDate(t.dueDate,{showTime:true})}</p>}{t.blocker&&<p className="mt-2 rounded-lg bg-rose-950/40 p-2 text-xs text-rose-200">مانع: {t.blocker}</p>}</button>{status!=='done'&&<button onClick={()=>complete(t)} className="mt-3 flex items-center gap-1 text-xs font-bold text-emerald-300"><CheckCircle2 className="h-4 w-4"/>تکمیل کار</button>}</article>)}</div></section>)}</div>
 {edit&&<AtelierModal title={edit.id?'ویرایش کار':'کار جدید'} onClose={()=>setEdit(null)}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="پروژه"><select disabled={!!edit.id} required className={fieldClass} value={edit.studioProjectId} onChange={e=>setEdit({...edit,studioProjectId:e.target.value})}><option value="">انتخاب پروژه</option>{projects.map(p=><option key={p.id} value={p.id}>{p.projectNumber} — {p.title}</option>)}</select></Field><Field label="عنوان کار"><input required className={fieldClass} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></Field><Field label="مرحله"><select className={fieldClass} value={edit.stage} onChange={e=>setEdit({...edit,stage:e.target.value})}>{['pre_production','shooting','raw_backup','selection','retouch','video_edit','album_print','final_qc','delivery'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="اولویت"><select className={fieldClass} value={edit.priority} onChange={e=>setEdit({...edit,priority:e.target.value})}><option value="low">کم</option><option value="medium">عادی</option><option value="high">مهم</option><option value="urgent">فوری</option></select></Field><Field label="مسئول"><select className={fieldClass} value={edit.assignedPersonnelId||''} onChange={e=>setEdit({...edit,assignedPersonnelId:e.target.value})}><option value="">تعیین نشده</option>{personnel.map(p=><option key={p.id} value={p.id}>{p.fullName}</option>)}</select></Field><JalaliDatePicker label="مهلت" value={edit.dueDate} onChange={d=>setEdit({...edit,dueDate:d?.toISOString()||''})}/><Field label="مانع / وابستگی متنی"><input className={fieldClass} value={edit.blocker||''} onChange={e=>setEdit({...edit,blocker:e.target.value})}/></Field><Field label="وضعیت"><select className={fieldClass} value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="open">باز</option><option value="in_progress">در حال انجام</option><option value="done">تکمیل</option><option value="cancelled">لغو</option></select></Field><div className="sm:col-span-2"><Field label="توضیحات"><textarea className={fieldClass} value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></Field></div><div className="flex gap-2 sm:col-span-2"><button className="rounded-xl bg-cyan-600 px-5 py-2.5 font-bold">ذخیره</button><button type="button" onClick={()=>setEdit(null)} className="rounded-xl border border-slate-700 px-5">انصراف</button></div></form></AtelierModal>}
 </div>}
