"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { RefreshCw, WalletCards } from "lucide-react";
import { atelierPrompt } from "@/lib/atelierFeedback";
import { atelierLabel } from "@/lib/atelierLabels";
import { JalaliDatePicker } from "@/components/ui/JalaliDatePicker";

type FinanceData = Record<string, any>;
const TABS = ["نمای کلی", "حساب‌ها و صندوق‌ها", "دریافت‌ها", "پرداخت‌ها", "هزینه‌ها", "مطالبات", "بدهی‌ها", "حقوق و دستمزد", "سود قراردادها", "گردش نقدینگی", "گزارش مالی"] as const;
const money = (value: unknown) => `${Number(value || 0).toLocaleString("fa-IR")} تومان`;
const date = (value: unknown) => value ? new Intl.DateTimeFormat("fa-IR-u-ca-persian", { dateStyle: "medium" }).format(new Date(String(value))) : "—";
const inputClass = "atelier-input w-full px-3 py-2.5 text-sm";

function Metric({ title, value, tone = "normal" }: { title: string; value: unknown; tone?: "normal" | "good" | "bad" }) {
  return <div className={`atelier-card p-4 ${tone === "bad" ? "border-red-800/70" : tone === "good" ? "border-emerald-900/70" : ""}`}><p className="text-xs text-zinc-500">{title}</p><p className={`mt-2 text-lg font-black ${tone === "bad" ? "text-red-300" : tone === "good" ? "text-emerald-300" : "text-white"}`}>{money(value)}</p></div>;
}
function Empty({ children = "داده‌ای برای نمایش وجود ندارد." }: { children?: string }) { return <div className="rounded-2xl border border-dashed border-zinc-800 p-8 text-center text-sm text-zinc-500">{children}</div>; }
function Table({ headers, rows }: { headers: string[]; rows: Array<Array<React.ReactNode>> }) {
  if (!rows.length) return <Empty />;
  return <div className="overflow-x-auto rounded-2xl border border-zinc-800"><table className="w-full min-w-[720px] text-right text-sm"><thead className="bg-zinc-950 text-xs text-zinc-500"><tr>{headers.map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-zinc-900">{rows.map((cells, i) => <tr key={i} className="bg-[#0b0b0d] hover:bg-red-950/10">{cells.map((cell, j) => <td key={j} className="px-4 py-3 text-zinc-300">{cell}</td>)}</tr>)}</tbody></table></div>;
}
function Bars({ rows }: { rows: Array<{ label: string; amount: number }> }) {
  const max = Math.max(1, ...rows.map((row) => Math.abs(row.amount)));
  if (!rows.length) return <Empty />;
  return <div className="space-y-3">{rows.map((row) => <div key={row.label}><div className="mb-1 flex justify-between text-xs"><span className="text-zinc-400">{row.label}</span><span>{money(row.amount)}</span></div><div className="h-2 overflow-hidden rounded-full bg-zinc-900"><div className="h-full rounded-full bg-gradient-to-l from-red-500 to-red-900 shadow-[0_0_12px_rgba(239,68,68,.35)]" style={{ width: `${Math.max(3, Math.abs(row.amount) / max * 100)}%` }} /></div></div>)}</div>;
}

export function AtelierFinanceView({ initialContractId }: { initialContractId?: string | null }) {
  const [tab, setTab] = useState<(typeof TABS)[number]>("نمای کلی");
  const [data, setData] = useState<FinanceData | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [form, setForm] = useState<Record<string, string>>({ sourceType: "contract", sourceId: initialContractId || "", paymentMethod: "card_transfer", paid: "false" });
  const load = useCallback(async () => {
    setBusy(true); setError("");
    try { const response = await fetch("/api/atelier/finance", { cache: "no-store" }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || "دریافت اطلاعات مالی ناموفق بود."); setData(body.data); }
    catch (e) { setError(e instanceof Error ? e.message : "خطای نامشخص"); } finally { setBusy(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (initialContractId) { setTab("دریافت‌ها"); setForm((old) => ({ ...old, sourceType: "contract", sourceId: initialContractId })); } }, [initialContractId]);
  const post = async (url: string, body: Record<string, unknown>, method = "POST") => {
    setBusy(true); setError("");
    try { const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "ثبت عملیات ناموفق بود."); setForm({ sourceType: "contract", paymentMethod: "card_transfer", paid: "false" }); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : "خطای نامشخص"); } finally { setBusy(false); }
  };
  const sourceOptions = data?.receivableSources || [];
  const summary = data?.summary || {};
  const actualFlow = useMemo(() => (data?.cashflow || []).map((row: any) => ({ label: row.period, amount: Number(row.actualIn) - Number(row.actualOut) })), [data]);
  const action = (label: string, onClick: () => void | Promise<void>) => <button disabled={busy} onClick={() => void onClick()} className="rounded-xl bg-red-700 px-3 py-2 text-xs font-bold text-white transition hover:bg-red-600 disabled:opacity-50">{label}</button>;
  const mutateAccount = async (body: Record<string, unknown>) => { const response = await fetch("/api/accounts", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error || "ویرایش حساب انجام نشد."); await load(); };
  const configureInstallments = async (row: any) => {
    const count = Number(await atelierPrompt("تعداد اقساط", "2"));
    const first = await atelierPrompt("تاریخ اولین سررسید (YYYY-MM-DD)", new Date().toISOString().slice(0, 10));
    if (!Number.isInteger(count) || count < 1 || count > 24 || !first) return;
    const base = Math.floor(Number(row.remainingAmount) / count), remainder = Number(row.remainingAmount) - base * count;
    const installments = Array.from({ length: count }, (_, index) => { const due = new Date(`${first}T12:00:00Z`); due.setUTCMonth(due.getUTCMonth() + index); return { title: `قسط ${index + 1}`, amount: base + (index === count - 1 ? remainder : 0), dueDate: due.toISOString() }; });
    await post(`/api/atelier/finance/contracts/${row.sourceId}/installments`, { installments }, "PUT");
  };

  const overview = <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric title="نقدینگی فعلی" value={summary.liquidity} /><Metric title="دریافت این ماه" value={summary.receivedThisMonth} tone="good" /><Metric title="پرداخت این ماه" value={summary.paidThisMonth} tone="bad" /><Metric title="مطالبات مشتریان" value={summary.receivable} /><Metric title="بدهی به پرسنل" value={summary.personnelDebt} tone="bad" /><Metric title="بدهی تجهیزات اجاره‌ای" value={summary.rentalDebt} tone="bad" /><Metric title="جریان نقدی خالص" value={summary.netCashflow} tone={summary.netCashflow >= 0 ? "good" : "bad"} /><Metric title="هزینه‌های این ماه" value={summary.expensesThisMonth} /><Metric title="درآمد قراردادهای این ماه" value={summary.contractedThisMonth} /><Metric title="سود تخمینی این ماه" value={summary.estimatedProfitThisMonth} tone="good" /></div><div className="grid gap-4 lg:grid-cols-2"><section className="atelier-card p-5"><h2 className="mb-4 font-black">روند جریان نقدی</h2><Bars rows={actualFlow} /></section><section className="atelier-card p-5"><h2 className="mb-4 font-black">چشم‌انداز نقدینگی</h2><div className="grid gap-3 sm:grid-cols-2">{(data?.forecast || []).map((row: any) => <div key={row.days} className="rounded-xl border border-zinc-800 p-3"><p className="text-xs text-zinc-500">{row.days.toLocaleString("fa-IR")} روز آینده</p><p className="mt-2 text-sm text-emerald-300">ورودی {money(row.incoming)}</p><p className="text-sm text-red-300">خروجی {money(row.outgoing)}</p><p className="mt-1 font-black">خالص {money(row.net)}</p></div>)}</div></section></div></div>;

  const accounts = <div className="space-y-4"><form className="atelier-card grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5" onSubmit={(e) => { e.preventDefault(); void post("/api/accounts", { name: form.accountName, type: form.accountType || "bank", balance: Number(form.openingBalance || 0), isDefault: form.isDefault === "true" }); }}><input required className={inputClass} placeholder="نام حساب یا صندوق" value={form.accountName || ""} onChange={(e) => setForm({ ...form, accountName: e.target.value })} /><select className={inputClass} value={form.accountType || "bank"} onChange={(e) => setForm({ ...form, accountType: e.target.value })}><option value="bank">حساب بانکی</option><option value="cash">صندوق نقدی</option><option value="pos">کارت‌خوان</option></select><input className={inputClass} type="number" min="0" placeholder="موجودی آغازین" value={form.openingBalance || ""} onChange={(e) => setForm({ ...form, openingBalance: e.target.value })} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isDefault === "true"} onChange={(e) => setForm({ ...form, isDefault: String(e.target.checked) })} /> حساب پیش‌فرض</label><button className="rounded-xl bg-red-700 px-4 py-2 font-bold">افزودن حساب</button></form><Table headers={["نام", "نوع", "موجودی", "وضعیت", "عملیات"]} rows={(data?.accounts || []).map((row: any) => [row.name, atelierLabel(row.type), money(row.balance), row.isDefault ? "پیش‌فرض" : "فعال", <div key="actions" className="flex gap-2">{action("ویرایش", async () => { const name = await atelierPrompt("نام حساب", row.name); if (name?.trim()) await mutateAccount({ id: row.id, name: name.trim(), type: row.type, bankName: row.bankName, accountNumber: row.accountNumber }); })}{!row.isDefault && action("پیش‌فرض", () => mutateAccount({ id: row.id, isDefault: true }))}{action("بایگانی", () => fetch(`/api/accounts?id=${row.id}`, { method: "DELETE" }).then(load))}</div>])} /></div>;

  const receipts = <div className="space-y-4"><form className="atelier-card grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-6" onSubmit={(e) => { e.preventDefault(); const source = sourceOptions.find((row: any) => row.sourceId === form.sourceId); void post("/api/atelier/finance/receipts", { sourceType: source?.sourceType, sourceId: form.sourceId, accountId: form.accountId, amount: Number(form.amount), paymentMethod: form.paymentMethod, paidAt: form.transactionDate || new Date().toISOString(), referenceNumber: form.referenceNumber, idempotencyKey: crypto.randomUUID() }); }}><select required className={`${inputClass} xl:col-span-2`} value={form.sourceId || ""} onChange={(e) => setForm({ ...form, sourceId: e.target.value })}><option value="">انتخاب قرارداد/مراجعه</option>{sourceOptions.map((row: any) => <option key={`${row.sourceType}:${row.sourceId}`} value={row.sourceId}>{row.title} — مانده {money(row.remainingAmount)}</option>)}</select><select required className={inputClass} value={form.accountId || ""} onChange={(e) => setForm({ ...form, accountId: e.target.value })}><option value="">حساب مقصد</option>{(data?.accounts || []).map((row: any) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input required className={inputClass} type="number" min="1" placeholder="مبلغ دریافت" value={form.amount || ""} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><JalaliDatePicker label="تاریخ دریافت" value={form.transactionDate || null} onChange={(value) => setForm({ ...form, transactionDate: value?.toISOString() || "" })} /><button className="rounded-xl bg-emerald-700 px-4 py-2 font-bold">ثبت دریافت</button></form><Table headers={["تاریخ", "منبع", "حساب", "مبلغ", "روش"]} rows={(data?.receipts || []).map((row: any) => [date(row.paymentDate), row.source?.title || "دریافت", row.accountName, money(row.amount), atelierLabel(row.paymentMethod)])} /></div>;

  const expenseForm = <form className="atelier-card grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-6" onSubmit={(e) => { e.preventDefault(); void post("/api/atelier/finance/expenses", { title: form.expenseTitle, category: form.category || "general", amount: Number(form.amount), expenseDate: form.transactionDate || new Date().toISOString(), dueDate: form.dueDate || null, paid: form.paid === "true", accountId: form.paid === "true" ? form.accountId : null, notes: form.notes, idempotencyKey: crypto.randomUUID() }); }}><input required className={`${inputClass} xl:col-span-2`} placeholder="عنوان هزینه" value={form.expenseTitle || ""} onChange={(e) => setForm({ ...form, expenseTitle: e.target.value })} /><input className={inputClass} placeholder="دسته‌بندی" value={form.category || ""} onChange={(e) => setForm({ ...form, category: e.target.value })} /><input required className={inputClass} type="number" min="1" placeholder="مبلغ" value={form.amount || ""} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><JalaliDatePicker label="سررسید" value={form.dueDate || null} onChange={(value) => setForm({ ...form, dueDate: value?.toISOString() || "" })} /><button className="rounded-xl bg-red-700 px-4 py-2 font-bold">ثبت هزینه</button></form>;
  const expenses = <div className="space-y-4">{expenseForm}<Table headers={["تاریخ", "عنوان", "دسته", "مبلغ", "پرداخت‌شده", "مانده", "عملیات"]} rows={(data?.expenses || []).map((row: any) => [date(row.expenseDate), row.title, atelierLabel(row.category), money(row.amount), money(row.paidAmount), money(row.remainingAmount), row.remainingAmount > 0 ? action("پرداخت", async () => { const accountId = await atelierPrompt("شناسه حساب پرداخت‌کننده", data?.accounts?.[0]?.id || ""); const amount = await atelierPrompt("مبلغ پرداخت", String(row.remainingAmount)); if (accountId && amount) await post(`/api/atelier/finance/expenses/${row.id}/payments`, { accountId, amount: Number(amount), idempotencyKey: crypto.randomUUID() }); }) : "تسویه"])} /></div>;
  const payments = <Table headers={["تاریخ", "شرح", "حساب", "مبلغ", "روش"]} rows={(data?.payments || []).map((row: any) => [date(row.paymentDate), row.notes || atelierLabel(row.paymentType), row.accountName, money(row.amount), atelierLabel(row.paymentMethod)])} />;
  const receivables = <Table headers={["منبع", "عنوان", "سررسید", "مانده", "عملیات"]} rows={sourceOptions.map((row: any) => [row.sourceType === "contract" ? "قرارداد" : row.sourceType === "daily_visit" ? "مراجعه روزانه" : "رزرو", row.title, date(row.dueDate), money(row.remainingAmount), <div key="actions" className="flex gap-2">{action("ثبت دریافت", () => { setForm({ ...form, sourceId: row.sourceId }); setTab("دریافت‌ها"); })}{row.sourceType === "contract" && action("تنظیم اقساط", () => void configureInstallments(row))}</div>])} />;
  const payables = <Table headers={["عنوان", "دسته", "سررسید", "کل", "مانده", "عملیات"]} rows={(data?.payables || []).map((row: any) => [row.title, atelierLabel(row.category), date(row.dueDate), money(row.amount), money(row.remainingAmount), action("پرداخت", async () => { const accountId = await atelierPrompt("شناسه حساب پرداخت‌کننده", data?.accounts?.[0]?.id || ""); const amount = await atelierPrompt("مبلغ پرداخت", String(row.remainingAmount)); if (!accountId || !amount) return; const url = row.sourceType === "rental" ? `/api/atelier/finance/obligations/${row.sourceType}/${row.sourceId}` : `/api/atelier/finance/expenses/${row.id}/payments`; await post(url, { accountId, amount: Number(amount), idempotencyKey: crypto.randomUUID() }); })])} />;
  const salaries = <Table headers={["پرسنل", "منبع", "کار", "مبلغ", "پرداخت‌شده", "مانده", "عملیات"]} rows={(data?.salaries || []).map((row: any) => [row.personnelName, row.sourceLabel, row.sourceTitle, money(row.totalCalculated), money(row.paidAmount), money(row.remainingAmount), row.remainingAmount > 0 ? action("پرداخت", async () => { const accountId = await atelierPrompt("شناسه حساب", data?.accounts?.[0]?.id || ""); const amount = await atelierPrompt("مبلغ", String(row.remainingAmount)); if (accountId && amount) await post(`/api/atelier/finance/obligations/personnel_wage/${row.id}`, { accountId, amount: Number(amount), idempotencyKey: crypto.randomUUID() }); }) : "تسویه"])} />;
  const profitability = <Table headers={["قرارداد", "نوع پروژه", "درآمد", "هزینه", "سود", "حاشیه"]} rows={(data?.profitability || []).map((row: any) => [row.contractNumber, row.projectType || row.projectTitle, money(row.revenue), money(row.costs), <span key="profit" className={row.profit >= 0 ? "text-emerald-300" : "text-red-300"}>{money(row.profit)}</span>, `${Number(row.margin).toLocaleString("fa-IR", { maximumFractionDigits: 1 })}٪`])} />;
  const cashflow = <div className="grid gap-4 lg:grid-cols-2"><section className="atelier-card p-5"><h2 className="mb-4 font-black">جریان واقعی ماهانه</h2><Bars rows={actualFlow} /></section><section className="atelier-card p-5"><h2 className="mb-4 font-black">پیش‌بینی ۷/۳۰/۶۰/۹۰ روزه</h2><Bars rows={(data?.forecast || []).map((row: any) => ({ label: `${row.days.toLocaleString("fa-IR")} روز`, amount: row.net }))} /></section></div>;
  const reports = <div className="grid gap-4 lg:grid-cols-3"><section className="atelier-card p-5"><h2 className="mb-4 font-black">درآمد بر اساس منبع</h2><Bars rows={data?.reports?.incomeBySource || []} /></section><section className="atelier-card p-5"><h2 className="mb-4 font-black">هزینه بر اساس دسته</h2><Bars rows={data?.reports?.expensesByCategory || []} /></section><section className="atelier-card p-5"><h2 className="mb-4 font-black">سود بر اساس نوع پروژه</h2><Bars rows={data?.reports?.profitByProjectType || []} /></section></div>;
  const content: Record<string, React.ReactNode> = { "نمای کلی": overview, "حساب‌ها و صندوق‌ها": accounts, "دریافت‌ها": receipts, "پرداخت‌ها": payments, "هزینه‌ها": expenses, "مطالبات": receivables, "بدهی‌ها": payables, "حقوق و دستمزد": salaries, "سود قراردادها": profitability, "گردش نقدینگی": cashflow, "گزارش مالی": reports };

  return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="mb-1 flex items-center gap-2 text-xs font-bold text-red-400"><WalletCards className="h-4 w-4" /> مرکز مالی حکمت آتلیه</p><h1 className="text-2xl font-black text-white sm:text-3xl">مالی</h1><p className="mt-1 text-sm text-zinc-500">دریافت، پرداخت، مطالبات، بدهی و نقدینگی بر پایه اسناد مالی یکپارچه</p></div><button onClick={() => void load()} disabled={busy} className="atelier-icon-button" aria-label="به‌روزرسانی"><RefreshCw className={`h-5 w-5 ${busy ? "animate-spin" : ""}`} /></button></header>{error && <div role="alert" className="rounded-xl border border-red-800 bg-red-950/30 p-3 text-sm text-red-200">{error}</div>}<nav className="flex gap-2 overflow-x-auto pb-2" aria-label="بخش‌های مالی">{TABS.map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-xl border px-3 py-2 text-xs font-bold transition ${tab === item ? "border-red-600 bg-red-950/70 text-white shadow-[0_0_16px_rgba(220,38,38,.15)]" : "border-zinc-800 text-zinc-400 hover:border-red-950 hover:text-white"}`}>{item}</button>)}</nav>{!data && busy ? <div className="grid gap-3 sm:grid-cols-3">{[1,2,3].map((i) => <div key={i} className="h-28 animate-pulse rounded-2xl bg-zinc-900" />)}</div> : content[tab]}</div>;
}
