"use client";
import { useEffect,useMemo,useState } from "react";
import { CalendarPlus,Clock3,Plus,RefreshCw,UserRoundCheck } from "lucide-react";
import { JalaliDatePicker } from "@/components/ui/JalaliDatePicker";
import { MoneyInput } from "@/components/ui/MoneyInput";
import { AtelierModal,Field,fieldClass } from "@/components/studio/shared/AtelierModal";
import { toJalaliDate } from "@/lib/dateUtils";

type Lead={id:string;name:string;mobile:string;source?:string;eventType:string;desiredDate?:string;location?:string;budget?:string;stage:string;nextFollowUp?:string;lastContactAt?:string;lostReason?:string;notes?:string;catalogItemId?:string;convertedProjectId?:string};
const stages=[['lead','سرنخ'],['contact','تماس'],['consultation','مشاوره'],['proposal','پیشنهاد'],['contract_pending','منتظر قرارداد'],['booked','رزرو شده'],['lost','از دست رفته']] as const;
const empty={name:'',mobile:'',source:'',eventType:'wedding',desiredDate:'',location:'',budget:0,stage:'lead',nextFollowUp:'',lastContactAt:'',lostReason:'',notes:'',catalogItemId:''};
async function json(url:string,init?:RequestInit){const r=await fetch(url,init);const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||d.message||'عملیات ناموفق بود.');return d;}
export function LeadPipeline({onOpenProject}:{onOpenProject?:(id:string)=>void}){
 const[items,setItems]=useState<Lead[]>([]),[catalog,setCatalog]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[a,b]=await Promise.all([json('/api/studio/leads'),json('/api/studio/catalog')]);setItems(a.leads);setCatalog(b.items.filter((x:any)=>x.active&&x.kind!== 'addon'));}catch(e:any){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[]);
 const overdue=useMemo(()=>items.filter(x=>x.nextFollowUp&&new Date(x.nextFollowUp)<new Date()&&!['lost','converted','booked'].includes(x.stage)).length,[items]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await json(editing?`/api/studio/leads/${editing}`:'/api/studio/leads',{method:editing?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});setEditing(null);setForm(empty);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const convert=async(id:string)=>{if(!confirm('مشتری و پروژه از این سرنخ ساخته شود؟'))return;setBusy(true);try{const d=await json(`/api/studio/leads/${id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'convert'})});await load();onOpenProject?.(d.projectId)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const consultation=async(lead:Lead)=>{try{await json(`/api/studio/leads/${lead.id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'consultation',startTime:lead.nextFollowUp})});await load()}catch(e:any){setError(e.message)}};
 const edit=(x:Lead)=>{setEditing(x.id);setForm({...empty,...x,budget:Number(x.budget||0),desiredDate:x.desiredDate||'',nextFollowUp:x.nextFollowUp||'',lastContactAt:x.lastContactAt||''})};
 return <div className="space-y-5" dir="rtl"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-black text-white">سرنخ‌ها و CRM</h1><p className="mt-1 text-sm text-slate-400">از اولین تماس تا رزرو قطعی، بدون ساخت مشتری تکراری</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-slate-700 p-2.5" aria-label="تازه‌سازی"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/></button><button onClick={()=>{setForm(empty);setEditing('new')}} className="flex items-center gap-2 rounded-xl bg-cyan-600 px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4"/>سرنخ جدید</button></div></header>
 {error&&<p className="rounded-xl border border-rose-500/40 bg-rose-950/30 p-3 text-sm text-rose-200">{error}</p>}
 <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-400">سرنخ باز</p><b className="mt-1 block text-2xl text-white">{items.filter(x=>!['lost','converted'].includes(x.stage)).length.toLocaleString('fa-IR')}</b></div><div className="rounded-2xl border border-amber-500/30 bg-amber-950/20 p-4"><p className="text-xs text-amber-300">پیگیری عقب‌افتاده</p><b className="mt-1 block text-2xl text-amber-100">{overdue.toLocaleString('fa-IR')}</b></div><div className="rounded-2xl border border-emerald-500/30 bg-emerald-950/20 p-4"><p className="text-xs text-emerald-300">تبدیل‌شده</p><b className="mt-1 block text-2xl text-emerald-100">{items.filter(x=>x.stage==='converted').length.toLocaleString('fa-IR')}</b></div></div>
 <div className="flex gap-3 overflow-x-auto pb-3">{stages.map(([id,label])=><section key={id} className="min-w-[280px] flex-1 rounded-2xl border border-slate-800 bg-slate-900/70 p-3"><h2 className="mb-3 flex items-center justify-between font-bold text-white"><span>{label}</span><span className="rounded-full bg-slate-800 px-2 text-xs">{items.filter(x=>x.stage===id).length.toLocaleString('fa-IR')}</span></h2><div className="space-y-2">{items.filter(x=>x.stage===id).map(x=><article key={x.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><button onClick={()=>edit(x)} className="w-full text-right"><b className="text-sm text-white">{x.name}</b><p className="mt-1 text-xs text-slate-400" dir="ltr">{x.mobile}</p><p className="mt-2 text-xs text-slate-300">{x.eventType} {x.desiredDate?`· ${toJalaliDate(x.desiredDate)}`:''}</p>{x.nextFollowUp&&<p className={`mt-2 flex items-center gap-1 text-xs ${new Date(x.nextFollowUp)<new Date()?'text-amber-300':'text-slate-400'}`}><Clock3 className="h-3.5 w-3.5"/>پیگیری: {toJalaliDate(x.nextFollowUp,{showTime:true})}</p>}</button><div className="mt-3 grid grid-cols-2 gap-2">{!['booked','lost'].includes(x.stage)&&<button onClick={()=>consultation(x)} className="flex items-center justify-center gap-1 rounded-lg bg-blue-600/15 py-2 text-xs font-bold text-blue-300"><CalendarPlus className="h-4 w-4"/>رزرو مشاوره</button>}{['booked','contract_pending','proposal'].includes(x.stage)&&<button onClick={()=>convert(x.id)} className="flex items-center justify-center gap-1 rounded-lg bg-emerald-600/20 py-2 text-xs font-bold text-emerald-300"><UserRoundCheck className="h-4 w-4"/>تبدیل به پروژه</button>}</div></article>)}</div></section>)}</div>
 {editing&&<AtelierModal title={editing==='new'?'ثبت سرنخ جدید':'ویرایش سرنخ'} onClose={()=>setEditing(null)}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="نام و نام خانوادگی"><input required className={fieldClass} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="شماره همراه"><input required inputMode="tel" dir="ltr" className={fieldClass} value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></Field><Field label="منبع آشنایی"><input className={fieldClass} value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Field><Field label="نوع پروژه"><select className={fieldClass} value={form.eventType} onChange={e=>setForm({...form,eventType:e.target.value})}><option value="wedding">عروسی</option><option value="portrait">پرتره</option><option value="commercial">تجاری</option><option value="child">کودک و بارداری</option><option value="event">رویداد</option></select></Field><JalaliDatePicker label="تاریخ مدنظر" value={form.desiredDate} onChange={d=>setForm({...form,desiredDate:d?.toISOString()||''})}/><JalaliDatePicker label="پیگیری بعدی" value={form.nextFollowUp} onChange={d=>setForm({...form,nextFollowUp:d?.toISOString()||''})}/><Field label="بودجه تقریبی"><MoneyInput value={form.budget} onChange={budget=>setForm({...form,budget})} unit="تومان"/></Field><Field label="پکیج پیشنهادی"><select className={fieldClass} value={form.catalogItemId} onChange={e=>setForm({...form,catalogItemId:e.target.value})}><option value="">انتخاب نشده</option>{catalog.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="مرحله"><select className={fieldClass} value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{stages.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><Field label="لوکیشن"><input className={fieldClass} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field>{form.stage==='lost'&&<Field label="علت از دست رفتن"><input required className={fieldClass} value={form.lostReason} onChange={e=>setForm({...form,lostReason:e.target.value})}/></Field>}<div className="sm:col-span-2"><Field label="یادداشت"><textarea className={`${fieldClass} min-h-24`} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className="flex gap-2 sm:col-span-2"><button disabled={busy} className="rounded-xl bg-cyan-600 px-5 py-2.5 font-bold text-white disabled:opacity-50">ذخیره</button><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border border-slate-700 px-5 py-2.5 text-slate-300">انصراف</button></div></form></AtelierModal>}
 </div>;
}
