"use client";

import { useEffect, useState } from "react";
import { BarChart3, Coins, PackageCheck, Users, Wrench } from "lucide-react";
import { formatMoney } from "@/lib/dateUtils";

const labels: Record<string, string> = { lead: "سرنخ", contact: "تماس", consultation: "مشاوره", proposal: "پیشنهاد", contract_pending: "در انتظار قرارداد", booked: "رزروشده", lost: "از دست‌رفته", converted: "تبدیل‌شده", active_project: "پروژه فعال", shooting: "روز عکاسی", in_post_production: "پس‌تولید", ready_for_review: "آماده بازبینی", approved: "تأییدشده", delivered: "تحویل‌شده", completed: "تکمیل‌شده", archived: "بایگانی", cancelled: "لغوشده" };

export function AtelierReportsView() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/studio/reports").then(response => response.json()).then(result => { if (!result.success) throw Error(result.error); setData(result.reports); }).catch(cause => setError(cause.message)); }, []);
  if (error) return <p className="rounded-xl bg-rose-950/30 p-4 text-rose-200">{error}</p>;
  if (!data) return <div className="h-40 animate-pulse rounded-2xl bg-slate-900"/>;
  return <div className="space-y-6">
    <header><h1 className="text-2xl font-black">گزارش‌های آتلیه</h1><p className="text-sm text-slate-400">شاخص‌های عملیاتی و مالی مبتنی بر منبع رسمی حسابداری</p></header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="نرخ تبدیل" value={`${data.crm.conversionRate.toLocaleString("fa-IR")}٪`}/>{data.finance && <><Metric label="درآمد قراردادی" value={formatMoney(data.finance.contracted)}/><Metric label="وصول" value={formatMoney(data.finance.collected)}/><Metric label="مطالبات" value={formatMoney(data.finance.outstanding)}/><Metric label="سود پروژه‌ها" value={formatMoney(data.finance.profit)}/></>}</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="پروژه فعال" value={data.projects.active.toLocaleString("fa-IR")}/><Metric label="تکمیل‌شده" value={data.projects.completed.toLocaleString("fa-IR")}/><Metric label="دارای تأخیر" value={data.projects.delayed.toLocaleString("fa-IR")}/><Metric label="میانگین زمان تحویل" value={`${data.projects.averageTurnaroundDays.toLocaleString("fa-IR")} روز`}/></div>
    <div className="grid gap-5 xl:grid-cols-3"><Section title="قیف CRM" icon={<BarChart3/>} data={data.crm.byStage} translate/><Section title="منبع سرنخ" icon={<Users/>} data={data.crm.bySource}/><Section title="دلایل از دست رفتن" icon={<BarChart3/>} data={data.crm.lostReasons}/></div>
    {data.finance && <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 className="flex items-center gap-2 p-5 font-black"><Coins className="h-5 w-5 text-emerald-400"/>سودآوری پروژه‌ها</h2><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-slate-950 text-slate-400"><tr><th className="p-3">پروژه</th><th>درآمد</th><th>وصول</th><th>هزینه</th><th>سود</th><th>مطالبات</th></tr></thead><tbody>{data.finance.profitability.map((row:any)=><tr key={row.id} className="border-t border-slate-800"><td className="p-3 font-bold text-white">{row.title}</td><td>{formatMoney(row.revenue)}</td><td>{formatMoney(row.collected)}</td><td>{formatMoney(row.cost)}</td><td className={row.profit>=0?"text-emerald-300":"text-rose-300"}>{formatMoney(row.profit)}</td><td>{formatMoney(row.outstanding)}</td></tr>)}</tbody></table></div></section>}
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="flex items-center gap-2 font-black"><Users className="h-5 w-5 text-purple-400"/>کارکرد عوامل</h2><div className="mt-4 space-y-2">{data.personnel.map((row:any)=><div key={row.id} className="rounded-xl bg-slate-950 p-3"><div className="flex justify-between"><b>{row.name}</b><span className="text-xs text-purple-300">{row.completedTasks.toLocaleString("fa-IR")} / {row.tasks.toLocaleString("fa-IR")} کار</span></div><p className="mt-1 text-xs text-slate-400">{row.projects.toLocaleString("fa-IR")} پروژه{row.wages !== null ? ` · دستمزد ${formatMoney(row.wages)} · مانده ${formatMoney(row.outstanding)}` : ""}</p></div>)}</div></section>
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="flex items-center gap-2 font-black"><Wrench className="h-5 w-5 text-amber-400"/>استفاده تجهیزات</h2><div className="mt-4 space-y-2">{data.equipment.utilization.map((row:any)=><div key={row.id} className="flex justify-between rounded-xl bg-slate-950 p-3"><span>{row.title}</span><span className="text-xs text-slate-400">{row.reservations.toLocaleString("fa-IR")} رزرو {row.damaged ? `· ${row.damaged.toLocaleString("fa-IR")} آسیب` : ""}</span></div>)}</div></section>
    </div>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="flex items-center gap-2 font-black"><PackageCheck className="h-5 w-5 text-cyan-400"/>عملکرد خدمات و پکیج‌ها</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.services.performance.map((row:any)=><div key={row.id} className="rounded-xl bg-slate-950 p-3"><div className="flex justify-between"><b>{row.name}</b><span className="text-xs text-cyan-300">{row.bookings.toLocaleString("fa-IR")} رزرو</span></div><p className="mt-2 text-xs text-slate-400">میانگین قرارداد {formatMoney(row.averageTicket)} · سود {formatMoney(row.profit)}</p></div>)}</div></section>
    {data.finance && <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 className="p-5 font-black">گردش نقدی ماهانه</h2><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-right text-sm"><thead className="bg-slate-950 text-slate-400"><tr><th className="p-3">ماه</th><th>قرارداد</th><th>وصول</th><th>هزینه</th><th>خالص نقدی</th></tr></thead><tbody>{data.finance.cashflow.map((row:any)=><tr key={row.month} className="border-t border-slate-800"><td className="p-3">{row.month}</td><td>{formatMoney(row.contracted)}</td><td>{formatMoney(row.collected)}</td><td>{formatMoney(row.expenses)}</td><td className={row.net>=0?"text-emerald-300":"text-rose-300"}>{formatMoney(row.net)}</td></tr>)}</tbody></table></div></section>}
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><small className="text-slate-400">{label}</small><b className="mt-2 block text-lg text-white">{value}</b></div>; }
function Section({ title, icon, data, translate = false }: { title: string; icon: React.ReactNode; data: Record<string, number>; translate?: boolean }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="flex items-center gap-2 font-black">{icon}{title}</h2><div className="mt-4 space-y-2">{Object.entries(data).length ? Object.entries(data).map(([key,value])=><div key={key} className="flex justify-between rounded-xl bg-slate-950 p-3"><span className="text-slate-300">{translate ? labels[key] || key : key}</span><b>{value.toLocaleString("fa-IR")}</b></div>) : <p className="text-sm text-slate-500">داده‌ای برای این بازه وجود ندارد.</p>}</div></section>; }
